### ISSUE TITLE
little change

### ISSUE THREAD

**Issue by Raptorzil** [darylturner/vault2pkcs12#2]
Hi.

you need to change : 	"github.com/mitchellh/packer/builder/azure/pkcs12" 
by : 	"github.com/hashicorp/packer/builder/azure/pkcs12"

**Comment by Raptorzil** [comment]
thanks for your code anyway =D

**Comment by darylturner** [comment]
Hi, thanks for letting me know. I no longer use this in my day-to-day since moving jobs. Hopefully this fixes the build for you.
